### ISSUE TITLE
Invalid syntax khi chạy lệnh khởi tạo model

### ISSUE THREAD

**Issue by khs123** [undertheseanlp/underthesea#239]
```
➜ underthesea data
Traceback (most recent call last):
  File "/home/khanhdv/.virtualenvs/spark/bin/underthesea", line 6, in <module>
    from underthesea.cli import main
  File "/home/khanhdv/.virtualenvs/spark/lib/python3.5/site-packages/underthesea/cli.py", line 32
    system_info = f"{platform.system()}{platform.release()}"
                                                           ^
SyntaxError: invalid syntax
```
 Mình bị lỗi này khi chạy lệnh trên, đã làm theo đúng hướng dẫn ở trang đầu tiên nhưng bị lỗi vậy.
Mình dùng ubuntu 16.04

**Comment by rain1024** [comment]
@khs123 Lỗi này xảy ra khi bạn dùng python dưới phiên bản 3.6

Từ phiên bản 1.1.15, underthesea chỉ hỗ trợ python 3.6+

Mình sẽ cập nhật lại document rõ ràng hơn trong các phiên bản sắp tới.

Thanks
