### ISSUE TITLE
Lỗi import underthesea 1.1.17 trong python 3.8

### ISSUE THREAD

**Issue by minhdc** [undertheseanlp/underthesea#307]
Mình bị lỗi khi import underthesea. Môi trường là Ubuntu 20.04 và Python3. Chi tiết lỗi :

`Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import underthesea
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/underthesea/__init__.py", line 24, in <module>
    from underthesea.sent_tokenize import sent_tokenize
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/underthesea/sent_tokenize/__init__.py", line 6, in <module>
    from nltk import PunktSentenceTokenizer
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/nltk/__init__.py", line 143, in <module>
    from nltk.chunk import *
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/nltk/chunk/__init__.py", line 157, in <module>
    from nltk.chunk.api import ChunkParserI
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/nltk/chunk/api.py", line 13, in <module>
    from nltk.parse import ParserI
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/nltk/parse/__init__.py", line 100, in <module>
    from nltk.parse.transitionparser import TransitionParser
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/nltk/parse/transitionparser.py", line 22, in <module>
    from sklearn.datasets import load_svmlight_file
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/sklearn/__init__.py", line 64, in <module>
    from .base import clone
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/sklearn/base.py", line 14, in <module>
    from .utils.fixes import signature
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 14, in <module>
    from . import _joblib
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/sklearn/utils/_joblib.py", line 22, in <module>
    from ..externals import joblib
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/sklearn/externals/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/sklearn/externals/joblib/parallel.py", line 28, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 22, in <module>
    from .executor import get_memmapping_executor
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/sklearn/externals/joblib/executor.py", line 14, in <module>
    from .externals.loky.reusable_executor import get_reusable_executor
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/sklearn/externals/joblib/externals/loky/__init__.py", line 12, in <module>
    from .backend.reduction import set_loky_pickler
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/sklearn/externals/joblib/externals/loky/backend/reduction.py", line 125, in <module>
    from sklearn.externals.joblib.externals import cloudpickle  # noqa: F401
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 167, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/home/extreme45nm/.local/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 148, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)`

**Comment by rain1024** [comment]
Hi @minhdc 

Bạn cài đặt underthesea như thế nào?

> `Python 3.8.2 (default, Jul 16 2020, 14:00:26)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

Hiện tại, underthesea đang hỗ trợ **python 3.6** bạn nhé. Bạn dùng `venv` hoặc `conda` để active python 3.6 rồi test lại thử xem

**Comment by minhdc** [comment]
@rain1024 cảm ơn bạn, mình xài python 3.8.2 thì cài ok (pip install) nhưng chạy bị xịt. còn python 3.7.6 trong venv thì oke.

**Comment by rain1024** [comment]
> File "/home/extreme45nm/.local/lib/python3.8/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py", line 148, in _make_cell_set_template_code
return types.CodeType(
TypeError: an integer is required (got type bytes)`

@minhdc có lẽ API của pickle có gì thay đổi trong python 3.8. Mình sẽ xem xét này issue khi underthesea hỗ trợ python 3.8 bạn nhé
