### ISSUE TITLE
Lỗi khi tải model, dataset do truyền vào sai argument (1.3.4)

### ISSUE THREAD

**Issue by Daocuong-main** [undertheseanlp/underthesea#521]
```
(opencv) C:\Windows\system32>underthesea download-model SA_BANK
2022-03-03 21:38:24,615 https://www.dropbox.com/s/yo6sf6ofpdb3hlh/sa_svm_uts2017_bank_20190611.zip?dl=1 not found in cache, downloading to C:\Users\Cuong\AppData\Local\Temp\tmp0w3io0vh
100%|██████████████████████████████████████████████████████████████████████| 21857637/21857637 [00:20<00:00, 1075242.84B/s]
2022-03-03 21:38:47,099 copying C:\Users\Cuong\AppData\Local\Temp\tmp0w3io0vh to cache at C:\Users\Cuong\.underthesea\models\sa_svm_uts2017_bank_20190611.zip?dl=1
Traceback (most recent call last):
  File "d:\anaconda3\envs\opencv\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\anaconda3\envs\opencv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\opencv\Scripts\underthesea.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\envs\opencv\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "d:\anaconda3\envs\opencv\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "d:\anaconda3\envs\opencv\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda3\envs\opencv\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda3\envs\opencv\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "d:\anaconda3\envs\opencv\lib\site-packages\underthesea\cli.py", line 27, in download_model
    ModelFetcher.download(model)
  File "d:\anaconda3\envs\opencv\lib\site-packages\underthesea\model_fetcher.py", line 125, in download
    cached_path(url, cache_dir=cache_dir)
  File "d:\anaconda3\envs\opencv\lib\site-packages\underthesea\file_utils.py", line 34, in cached_path
    return get_from_cache(url_or_filename, dataset_cache)
  File "d:\anaconda3\envs\opencv\lib\site-packages\underthesea\file_utils.py", line 94, in get_from_cache
    shutil.copyfile(temp_filename, str(cache_path))
  File "d:\anaconda3\envs\opencv\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Cuong\\.underthesea\\models\\sa_svm_uts2017_bank_20190611.zip?dl=1'
```
Mình để ý rằng lỗi có lẽ nằm ở cuối đường dẫn truyền vào, đáng lẽ là `C:\\Users\\Cuong\\.underthesea\\models\\sa_svm_uts2017_bank_20190611.zip` nhưng bị thêm `?dl=1`  dư thừa từ đường dẫn `https://www.dropbox.com/s/yo6sf6ofpdb3hlh/sa_svm_uts2017_bank_20190611.zip?dl=1`

**Comment by rain1024** [comment]
Có lẽ lỗi này liên quan đến windows, hiện tại mình thử trên Ubuntu vẫn chạy okie

```
$ underthesea download-model SA_BANK
$ ls ~/.underthesea/models/SA_BANK
metadata.json  pipeline.joblib	y_encoder.joblib
```
